portafolio/urls.py
from django.urls import path
from django.views.generic import TemplateView
from portafolio.views import HomeView, AlbumView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<slug>/', AlbumView.as_view(), name='album')

]

src/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('portafolio.urls', 'portafolio'), namespace='portafolio')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

portafolio/models.py
import uuid
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit
from django.contrib.auth.models import User

class Album(models.Model):
    nombre = models.CharField(max_length=30, verbose_name="Nombre")
    slug = models.SlugField(unique=True)

    publicado = models.BooleanField(default=True, verbose_name="Publicado")
    foto_destacada = ProcessedImageField(upload_to='albums',
                                    processors=[ResizeToFill(450, 450)],
                                    format='JPEG',
                                    options={'quality': 90},
                                    null=True,
                                    blank=True)
    descripcion = models.TextField(max_length=500, blank=True)
    
    creacion = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Fecha de Creación")
    modificacion = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Última Modificación")

    class Meta:
        verbose_name = 'Álbum'
        verbose_name_plural = 'Álbumes'

    def __str__(self):
        return self.nombre

class Foto(models.Model):
    titulo = models.CharField(max_length=50, verbose_name="Título")
    slug = models.SlugField(unique=True)
    publicada = models.BooleanField(default=True, verbose_name="Publicada")
    album = models.ForeignKey('Album', on_delete=models.SET_NULL, blank=True, null=True, related_name='fotos')
    imagen = ProcessedImageField(upload_to='fotos', processors=[ResizeToFit(1280)], format='JPEG', options={'quality': 70})
    imagen_450 = ImageSpecField(source='imagen',
                                processors=[ResizeToFill(450,450)],
                                format='JPEG',
                                options={'quality':80},)

    creacion = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Fecha de Creación")
    modificacion = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Última Modificación")

    class Meta:
        verbose_name = 'Foto'
        verbose_name_plural = 'Fotos'

    def __str__(self):
        return self.titulo

    def albumNombre(self):
        try:
            return self.album.nombre
        except:
            return 'undefined'
    

portafolio/views.py
from django.shortcuts import render
from .models import Album, Foto
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView, TemplateView

class HomeView(TemplateView):

    template_name = 'principal/home.html'

    def get_context_data(self, **kwargs):

        context = super(HomeView, self).get_context_data(**kwargs)
        context['albumes'] = Album.objects.filter(publicado=True)
        return context

class AlbumView(TemplateView):

    template_name = 'principal/album.html'

    def get_context_data(self, **kwargs):

        context = super(AlbumView, self).get_context_data(**kwargs)
        context['albumes'] = Album.objects.all()
        context['album'] = Album.objects.get(slug=self.kwargs['slug'])
        context['fotos'] = Foto.objects.filter(album=context['album'])
        return context

def handler404(request):
    assert isinstance(request, HttpRequest)
    return render(request, 'handler404.html', None, None, 404)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head_content %}
    <title>Default Home Title</title>
  {% endblock %}

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
  <link rel="icon" type="image/png"  href="{% static 'img/favicon.ico' %}" />
</head>

<body class="is-preload">
  <!-- Wrapper -->
  <div id="wrapper">

    <!-- Header -->
    <header id="header">
      <div class="inner" style="display:flex;justify-content:center;padding-bottom:5em;">
  
        <!-- Logo -->
        <a href="{% url 'portafolio:home' %}" class="logo">
          <span class="symbol"><img src="{% static 'img/logo.png' %}" alt="" /></span>
          <!-- <span class="title">María Gabriela Arráez</span> -->
        </a>
  
        <!-- Nav -->
        <nav style="z-index: 5">
          <ul>
            <li><a href="#menu">Menu</a></li>
          </ul>
        </nav>
  
      </div>
    </header>
  
    <!-- Menu -->
    {% include 'principal/menu.html' %}    
    
    <!-- Main -->
    <div id="main">
      {% block body_content %}
      {% endblock %}
    </div>


  <!-- Footer -->
  {% include 'principal/pie.html' %}    
  
</div>
  
  <!-- Scripts -->
  {% block page_script %}
  {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/browser.min.js' %}"></script>
  <script src="{% static 'js/breakpoints.min.js' %}"></script>
  <script src="{% static 'js/util.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/handler404.html
{% extends "base.html" %}

{% block head_content %}
<title>Pagina no encontrada</title>
{% endblock %}

{% block body_content %}

404

{% endblock %}

templates/principal/album.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
  <title>{{album.nombre}} || Maria Gabriela Arraez</title>
  <link rel="stylesheet" href="{% static 'external/photoswipe/photoswipe.css' %}"> 
  <link rel="stylesheet" href="{% static 'external/photoswipe/default-skin/default-skin.css' %}">
{% endblock %}

{% block body_content %}
<div class="inner">
  <header>
    <h1 style="margin-bottom: 10px !important">{{album.nombre}}</h1>
    <br>
    <p>{{album.descripcion}}</p>
  </header>
  <!-- Image -->
  <section class="tiles">
    {% for foto in fotos %}
      {% include 'principal/foto_tn.html' %}
    {% endfor %}
  </section>
</div>
{% endblock %}

{% block page_script %}
  <!-- PhotoSwipe -->
  <!-- Root element of PhotoSwipe. Must have class pswp. -->
  <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true" style="z-index: 9">

      <!-- Background of PhotoSwipe. 
            It's a separate element as animating opacity is faster than rgba(). -->
      <div class="pswp__bg"></div>

      <!-- Slides wrapper with overflow:hidden. -->
      <div class="pswp__scroll-wrap">

          <!-- Container that holds slides. 
              PhotoSwipe keeps only 3 of them in the DOM to save memory.
              Don't modify these 3 pswp__item elements, data is added later on. -->
          <div class="pswp__container">
              <div class="pswp__item"></div>
              <div class="pswp__item"></div>
              <div class="pswp__item"></div>
          </div>

          <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
          <div class="pswp__ui pswp__ui--hidden">

              <div class="pswp__top-bar">

                  <!--  Controls are self-explanatory. Order can be changed. -->

                  <div class="pswp__counter"></div>

                  <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                  <button class="pswp__button pswp__button--share" title="Share"></button>

                  <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                  <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                  <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                  <!-- element will get class pswp__preloader--active when preloader is running -->
                  <div class="pswp__preloader">
                      <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                          <div class="pswp__preloader__donut"></div>
                        </div>
                      </div>
                  </div>
              </div>

              <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                  <div class="pswp__share-tooltip"></div> 
              </div>

              <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
              </button>

              <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
              </button>

              <div class="pswp__caption">
                  <div class="pswp__caption__center"></div>
              </div>

          </div>

      </div>

  </div>
  <script>
      // build the json album images collection 
      window.djangoFotos = [
          {% for foto in fotos %}
              {
                  src: '{{ foto.imagen.url }}',
                  w:  '{{ foto.imagen.width }}',
                  h:  '{{ foto.imagen.height }}'
              },
          {% endfor %}
      ];
  </script>
  <script type="text/javascript">
    function pswpInit(startsAtIndex) {

      if (!startsAtIndex) {
          startsAtIndex = 0;
      }

      var pswpElement = document.querySelectorAll('.pswp')[0];

      // find is images are loaded from the server.
      if (window.djangoFotos && window.djangoFotos.length > 0) {
          // define options (if needed)
          var options = {
              // optionName: 'option value'
              // for example:
              index: startsAtIndex // start at first slide
          };

          // Initializes and opens PhotoSwipe
          var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, window.djangoFotos, options);
          gallery.init();
      }
    }
  </script>
  <script src="{% static 'external/photoswipe/photoswipe.min.js' %}"></script> 
  <script src="{% static 'external/photoswipe/photoswipe-ui-default.min.js' %}"></script>
{% endblock %}

templates/principal/album_tn.html
{% load static %}
<!-- <article class="style1"> -->
<article class="">
    <span class="image">
        <img src="{{album.foto_destacada.url}}" alt="" />
    </span>
    <a href="{% url 'portafolio:album' album.slug %}">
        <div class="content">
            <h2>{{album.nombre}}</h2>
            <!-- <p>{{album.descripcion}}</p> -->
        </div>
    </a>
</article>

templates/principal/foto_tn.html
{% load static %}
<!-- <div class="col-4">
    <span class="image fit">
        <img src="http://localhost:8000/media/{{foto.imagen_450}}" alt="" />
    </span>
</div> -->

<article class="">
    <span class="image">
        <img src="{{foto.imagen_450.url}}" alt="{{foto.slug}}" />
    </span>
    <!-- <a href="{{foto.imagen.url}}"> -->
    <a href="javascript:pswpInit({{ forloop.counter0 }});">
        <div class="content">
            <h2>{{foto.titulo}}</h2>
        </div>
    </a>
</article>

templates/principal/home.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
<title>Phantom by HTML5 UP</title>
{% endblock %}

{% block body_content %}
  <div class="inner">
    <section class="tiles">
        {% for album in albumes %}
          {% include 'principal/album_tn.html' %}
        {% endfor %}        
    </section>
    {% comment %}
    <div class="pagination" style="margin-top:30px">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
    {% endcomment %}
  </div>
{% endblock %}

templates/principal/menu.html
{% load static %}
<nav id="menu">
    <h2>Menu</h2>
    <ul>
      <li><a href="{% url 'portafolio:home' %}">Home</a></li>
      {% for album in albumes %}
        <li><a href="{% url 'portafolio:album' album.slug %}">{{album.nombre}}</a></li>
      {% endfor %}
    </ul>
  </nav>

templates/principal/pie.html
{% load static %}
<footer id="footer">
    <div class="inner">
      <section>
        <h2>Contáctame</h2>
        <form method="post" action="#">
          <div class="fields">
            <div class="field half">
              <input type="text" name="name" id="name" placeholder="Nombre" />
            </div>
            <div class="field half">
              <input type="email" name="email" id="email" placeholder="Email" />
            </div>
            <div class="field">
              <textarea name="message" id="message" placeholder="Mensaje"></textarea>
            </div>
          </div>
          <ul class="actions">
            <li><input type="submit" value="Enviar" class="primary" /></li>
          </ul>
        </form>
      </section>
      <section>
        <h2>Sígueme</h2>
        <ul class="icons">
          <li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
          <li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
          <li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
          <li><a href="#" class="icon style2 fa-phone"><span class="label">Phone</span></a></li>
          <li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
        </ul>
      </section>
      <ul class="copyright">
        <li>&copy; María Gabriela Arráez. All rights reserved</li>
        <li>Development: <a href="http://html5up.net">Elias Ablan</a></li>
      </ul>
    </div>
  </footer>